[build-system]
requires = ["setuptools>=72", "wheel", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "etos_environment_provider"
dynamic = ["version"]
description = "Environment Provider for ETOS."
authors = [{name = "Tobias Persson", email = "tobias.persson@axis.com"}]
license = { text  = "Apache License, Version 2.0" }
readme = "README.rst"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License"
]
requires-python = ">=3.13"
dependencies = [
    "cryptography>=50.0.0,<51.0.0",
    "jsontas>=1.4.1,<2.0.0",
    "packageurl-python~=0.11",
    "etcd3gw~=2.3",
    "etos-lib==5.5.1",
    "opentelemetry-api~=1.40",
    "opentelemetry-exporter-otlp~=1.40",
    "opentelemetry-sdk~=1.40",
]

[project.urls]
Documentation = "https://etos.readthedocs.io/"
Homepage = "https://github.com/eiffel-community/etos-environment-provider"
Repository = "https://github.com/eiffel-community/etos-environment-provider"

[project.optional-dependencies]
testing = ["pytest", "pytest-cov"]

[tool.black]
line-length = 100

[tool.build_sphinx]
source_dir = "docs"
build_dir = "build/sphinx"

[tool.devpi.upload]
no-vcs = 1
formats = "bdist_wheel"

[tool.flake8]
exclude = [".tox", "build", "dist", ".eggs", "docs/conf.py"]

[tool.pytest.ini_options]
addopts = "--cov etos_lib --cov-report term-missing --verbose"
norecursedirs = ["dist", "build", ".tox"]
testpaths = ["tests"]

[tool.setuptools_scm]
root = "."

[tool.setuptools.packages]
find = { where = ["src"], exclude = ["tests"] }
